# Generated by Django 4.1.7 on 2023-03-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(default='', max_length=100)),
                ('rok', models.IntegerField()),
                ('opis', models.TextField()),
            ],
            options={
                'ordering': ['nazwa'],
            },
        ),
    ]
