# Generated by Django 4.1.7 on 2023-04-04 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(default='', max_length=100)),
                ('rok', models.IntegerField()),
                ('opis', models.TextField()),
            ],
            options={
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(default='', max_length=50)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='gatunki',
            field=models.ManyToManyField(to='quickstart.gatunek'),
        ),
        migrations.AddField(
            model_name='film',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.producent'),
        ),
    ]
