# Generated by Django 4.1.7 on 2023-04-04 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0002_alter_film_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmy', to=settings.AUTH_USER_MODEL),
        ),
    ]
