# Generated by Django 4.1.7 on 2023-05-16 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0003_alter_film_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gatunki',
            field=models.ManyToManyField(null=True, to='quickstart.gatunek'),
        ),
        migrations.AlterField(
            model_name='film',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filmy', to=settings.AUTH_USER_MODEL),
        ),
    ]
