# Generated by Django 4.2.1 on 2023-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_film_gatunki_alter_film_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gatunki',
            field=models.ManyToManyField(to='quickstart.gatunek'),
        ),
    ]
